For testing and developing the function get_basic_clean_annotations_from_full

In [1]:
%load_ext autoreload
%autoreload 2

In [6]:
from pathlib import Path

import pandas as pd

from keller_zlatic_vnc.data_processing import find_quiet_periods
from keller_zlatic_vnc.data_processing import get_basic_clean_annotations_from_full
from keller_zlatic_vnc.data_processing import read_full_annotations

In [3]:
# Folder holding annotation data
annot_folder = r'/Volumes/bishoplab/projects/keller_vnc/data/full_annotations/em_volume_behavior_csv'

# Annotation file
annot_file = '18-02-15L1-behavior-ol.csv'

In [47]:
full_annotations = read_full_annotations(Path(annot_folder) / annot_file)
quiet_annots = find_quiet_periods(full_annotations, 30)
full_annotations = pd.concat([full_annotations, quiet_annots], ignore_index=True)

In [48]:
clean_annotations = get_basic_clean_annotations_from_full(full_annotations, clean_def='po')

In [49]:
(clean_annotations['beh'] == 'Q').sum()

9

In [50]:
clean_annotations

,start,end,beh,beh_before,beh_before_start,beh_before_end,beh_after,beh_after_start,beh_after_end
1,2,9,P,TL,0,6,H,11,12
2,11,12,H,P,2,9,TR,13,22
3,13,22,TR,H,11,12,B,23,33
6,46,50,P,TL,33,47,F,51,57
7,51,57,F,P,46,50,TR,59,62
...,...,...,...,...,...,...,...,...,...
516,7691,7786,Q,F,7680,7690,B,7787,7799
517,8046,8075,Q,TR,8041,8045,B,8076,8084
519,8925,9090,Q,F,8911,8924,TR,9091,9095
521,9449,9483,Q,F,9427,9448,P,9484,9493
524,10157,10229,Q,F,10146,10156,F,10230,10237